Article/Article/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('post.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Article/post/urls.py
from django.conf.urls import url
from .import views

app_name = 'post'

urlpatterns = [
    url(r'^$', views.list_view, name='list_view'),
    url('about/', views.about_view, name='about'), 
    url(r'^(?P<pk>\w+)/$', views.detail_view, name='detail'),
]

Article/post/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    # add author later


    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50]+'...'

Article/post/views.py
from django.shortcuts import render
from django.http import HttpResponse
from post.models import Article
# Create your views here.

def list_view(request):
    articles = Article.objects.all().order_by('-date')
    return render(request, 'post/post_list.html', {'articles':articles})

def about_view(request):
    return render(request, 'post/about.html')

def detail_view(request, pk):
    article = Article.objects.get(pk=pk)
    return render(request, 'post/post_detail.html', {'article':article})

Article/post/templates/post/about.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        Lorem ipsum dolor sit amet consectetur 
        adipisicing elit. Facere dolore dicta, 
        officia corporis hic reprehenderit adipisci!
        Excepturi, quos. Consequuntur rerum quos 
        aut fugit veniam at qui. Asperiores, eaque. Eum, quod.
    </div>
</div>
{% endblock %}

Article/post/templates/post/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Acme|Julius+Sans+One|McLaren|Tenor+Sans&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> -->
</head>
<body>

  <div class='container'>
      <!-- A grey horizontal navbar that becomes vertical on small screens -->
      <nav class="navbar navbar-expand-sm bg-dark">

          <!-- Links -->
          <ul class="navbar-nav" style="font-size: 40px;">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'post:list_view' %}"><img src="{% static 'images/home.png' %}" width='50' height="50" /></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'post:about' %}">About</a>
            </li>

          </ul>
        
        </nav>
  </div>
  
      {% block content %}

      {% endblock %}
</body>
</html>

Article/post/templates/post/post_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <h2>{{article.title}}</h2>
        <p>{{article.body}}</p>
        <p>{{article.date}}</p>
    </div>
</div>
{% endblock %}

Article/post/templates/post/post_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1><STROng>ARTICLE LISTS</STROng></h1>
        {% for article in articles %}
            <h2><a href="{% url 'post:detail' article.pk %}"><strong>{{article.title}}</strong></a></h2>
            <p>{{article.snippet}}</p>
            <p>{{article.date}}</p>
        {% endfor %}
    </div>
</div>    

{% endblock %}