MyStories/MyStories/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
# importing a sitemaps
from django.contrib.sitemaps.views import sitemap
from poems.sitemaps import PostSitemap

sitemaps = {
    'posts':PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('poems.urls', namespace='poems')),
    path('accounts/', include('accounts.urls')),
    path('sitemap.xml/', sitemap, {'sitemaps':sitemaps},
            name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

MyStories/accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
]

MyStories/poems/urls.py
from poems import views
from django.urls import path
# from django.views.generic import list_detail
# importing syndication function
from .feeds import LatestPostsFeed

app_name = 'poems'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('poems_view/', views.PoemListView.as_view(), name='poems_view'),
    path('gallery_view/', views.GalleryView.as_view(), name='gallery_view'),
    path('search_result/', views.SearchResultView.as_view(), name='search_result'),
    # url(r'^post_detail/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[\w-])/$', views.post_detail,name='post_detail'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail,name='post_detail'), 
    path('post_share/<int:id>/', views.post_share, name='post_share'),
    # url(r'^poems_view/$', views.poems_view, name='poems_view'), 
    # path('<id>/feed/', LatestPostsFeed(), name='post_feed'),
    path('post_share/', views.post_share, name='post_share'),
]

MyStories/poems/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,  self).get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User,related_name='posts', on_delete=models.CASCADE)
    body = models.TextField()
    thumb = models.ImageField(default='default.png', blank=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


    objects = models.Manager()  # The default manager
    published = PublishedManager() # our custom manager
    tags = TaggableManager()
    
    def get_absolute_url(self):
        return reverse('poems:post_detail', args=[self.publish.year,
                                                    self.publish.month,
                                                    self.publish.day,
                                                    self.slug])
    

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ('created',)
    
    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)
        


class Photo(models.Model):
    author = models.ForeignKey(User, default=None, null=True, on_delete=models.CASCADE)
    info = models.CharField(max_length=100)
    slug = models.SlugField(default='detail-view')
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)

    def show_img(self):
        return self.author

    def __str__(self):
        return self.info[:100] + '...'

class Poem(models.Model):
    author = models.ForeignKey(User, default=None, null=True, on_delete=models.CASCADE)
    actual_owner = models.CharField(max_length=80, default='author')
    title = models.CharField(max_length=50)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def content(self):
        return self.body



    

MyStories/poems/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ('name', 'email', 'body')

        widgets = {
        	'author':forms.TextInput(attrs={'class':'textinputclass'}),
        	'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea'})
        }

MyStories/poems/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Photo, Poem, Post, Comment
from .forms import EmailPostForm
from django.views import generic    
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# importing forms
from .forms import CommentForm #EmailPostForm
from django.core.mail import send_mail
# importing Q for search engine
from django.db.models import Q
# Create your views here.


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 8
    template_name = 'poems/blog.html'
  
class SearchResultView(ListView):
    model = Post
    template_name = 'poems/search_result.html'
    
    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Post.objects.filter(
            Q(title__icontains=query) | Q(body__icontains=query)
        )
        return object_list

# def post_list(request):
#     object_list = Post.published.all()
#     paginator = Paginator(object_list, 3) # 3 posts in each page
#     page = request.GET.get('page')
#     try:
#         posts = paginator.page(page)
#     except PageNotAnInteger:
#         # If page is not an integer deliver the first page
#         posts = paginator.page(1)
#     except EmptyPage:
#         # If page is out of range deliver last page of results
#         posts = paginator.page(paginator.num_pages)
        # return render(request,'poems/post_list.html',{'page': page,'posts': posts})


def post_share(request, id):

    # return render(request, 'poems/send.html')
    # return HttpResponse('form was submitted!')
    # Retrieve post by id
    post = get_object_or_404(Post, id=id, status='published')
    sent = False
    if request.method == 'POST':
        # Form was submitted
       
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # return HttpResponse('Form fields passed validation')
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments:{}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'ubuhobbit@gmail.com',[cd['to']], fail_silently=False)
            sent = True
            cd = form.cleaned_data
            # ... send email
    else:
        form = EmailPostForm()
    return render(request, 'poems/post_share.html', {'post': post,'form': form})


def post_detail(request, year, month, day, post):
    # return HttpResponse('You are in post list')
    post = get_object_or_404(Post, slug=post, 
                                    status='published',
                                    publish__year=year, 
                                    publish__month=month, 
                                    publish__day=day)
    # return HttpResponse('object taken')
    # List of active comments for this post
    comments = post.comments.filter(active=True).order_by('-created')
    new_comment = None
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, 'poems/post_detail.html', {'post':post,
                                                        'comments': comments,
                                                        'new_comment': new_comment,
                                                        'comment_form': comment_form}) 


class GalleryView(ListView):
    queryset = Photo.objects.all().order_by('-date')
    context_object_name = 'images'
    paginate_by = 50
    template_name = 'poems/cards-gallery.html'




# def poems_view(request):
#     poem = Poem.objects.all().order_by('-date')
#     paginator = Paginator(poem, 3) # 3 posts in each page
#     page = request.GET.get('page')
#     try:
#         posts = paginator.page(page)
#     except PageNotAnInteger:
#         # If page is not an integer deliver the first page
#         posts = paginator.page(1)
#     except EmptyPage:
#         # If page is out of range deliver last page of results
#         posts = paginator.page(paginator.num_pages)
#     return render(request, 'poems/poem_list.html', {'poem':poem})

class PoemListView(ListView):
    queryset = Poem.objects.all().order_by('-date')
    context_object_name = 'poem'
    paginate_by = 3
    template_name = 'poems/poem_list.html'
  

MyStories/poems/templates/poems/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <link href="https://fonts.googleapis.com/css?family=Righteous&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amaranth|Changa|Concert+One|Fredoka+One|Righteous&display=swap" rel="stylesheet">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'css/detail.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <!-- Custom icon font-->
    <link rel="stylesheet" href="{% static 'css/fontastic.css' %}">
    <!-- Google fonts - Open Sans-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <!-- Fancybox-->
    <link rel="stylesheet" href="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.css' %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'omg/favicon.png' %}">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
    
    <!-- links for cards gallery view -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css" />
    <link rel="stylesheet" href="{% static 'css/cards-gallery.css' %}">


    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> -->

    <title>{% block title %}Document{% endblock %}</title>
</head>
<body>
    <!-- <div class="container nav-content">
        <nav class="navbar navbar-expand-lg bg-none">
          <div class="id="navbarcollapse" class="collapse navbar-collapse"">
            <ul class="navbar-nav ml-auto">
              <li>
                <a class="navbar-brand" href="#">
                <img src="{% static 'img/tg.png' %}" width="50" height="50" alt="">
               </a>
              </li>
              <li>
                <a class="navbar-brand" href="#">
                <img src="{% static 'img/face.jpg' %}" width="50" height="50" alt="">
              </a>
              </li>
              <li>
                <a class="navbar-brand" href="#">
                <img src="{% static 'img/ins.png' %}" width="50" height="50" alt="">
                </a>
              </li>
              <li>
                <a class="navbar-brand" href="#">
                <img src="{% static 'img/twit.png' %}" width="50" height="50" alt="">
                </a>
              </li>
            </ul>       
          </div>
        </nav> 
    </div> -->
    <header class="header">
        <!-- Main Navbar-->
        <nav class="navbar navbar-expand-lg">
          <div class="search-area">
            <div class="search-area-inner d-flex align-items-center justify-content-center">
              <div class="close-btn"><i class="icon-close"></i></div>
              <div class="row d-flex justify-content-center">
                <div class="col-md-8">
                  <form action="#">
                    <div class="form-group">
                      <input type="search" name="search" id="search" placeholder="What are you looking for?">
                      <button type="submit" class="submit"><i class="icon-search-1"></i></button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
          <div class="container">
            <!-- Navbar Brand -->
            <div class="navbar-header d-flex align-items-center justify-content-between">
              <!-- Navbar Brand --><a href="{% url 'poems:post_list' %}" class="navbar-brand">Home</a>
              <!-- Toggle Button-->
              <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
            </div>
            <!-- Navbar Menu -->
            <div id="navbarcollapse" class="collapse navbar-collapse">
              <ul class="navbar-nav ml-auto">
                <li class="navbar-brand"><a href="{% url 'poems:gallery_view' %}" class="nav-link">Gallery</a>
                </li>
                <li class="navbar-brand"><a href="{% url 'poems:poems_view' %}" class="nav-link">Poems</a>
                </li>
              </ul>
              <div class="navbar-text">
                <ul>
                 <a href="#" class="search-btn"><i class="icon-search-1"></i></a>
                </ul>
              </div>
              <div>
                <ul class="langs navbar-text">
                  {% if user.is_authenticated %}
                  <div class="container">
                    <form class="logout-link" method="post" action="{% url 'accounts:logout' %}">
                      {% csrf_token %}
                      <button class='btn btn-primary'
                      type="submit">LOGOUT</button>
                    </form>
                  </div>
                  
                  {% else %}
                  <a href="{% url 'accounts:login' %}">Login</a><span></span><a href="{% url 'accounts:signup' %}">Sign Up</a>
                  {% endif %}
                </ul>
              </div>
            </div>
          </div>
        </nav>
      </header>
    
    <div class="container">
      <div class="row justify-content-md-center">
        <div class=".col-xl-9">  
            {% block content %}

            {% endblock %}
        </div>  
      </div>
    </div>
    <!-- Page Footer-->
    <footer class="main-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <div class="logo">
              <h6 class="text-white">Bootstrap Blog</h6>
            </div>
            <div class="contact-details">
              <p>Uzbekistan, Kashkadarya, Taragay 525</p>
              <p>Phone: + 998-90-667-66-25</p>
              <p>Give us to know: <a href="mailto:ubuhobbit@gmail.com">ubuhobbit@gmail.com</a></p>
              <ul class="social-menu">
                <li class="list-inline-item"><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-instagram"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-behance"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-pinterest"></i></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
            <div class="menus d-flex">
              <ul class="list-unstyled">
                <li> <a href="#">IMPERIA</a></li>
                <li> <a href="#">CIBERNET GROUP</a></li>
                <li> <a href="#">My informations</a></li>
                <li> <a href="#">Log in or Sign in</a></li>
              </ul>
              <ul class="list-unstyled">
                <li> <a href="#">Our Partners</a></li>
                <li> <a href="#">FAQ</a></li>
                <li> <a href="{% url 'admin:index' %}">For Admin</a></li>
                <li> <a href="#">Contact us</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
            <div class="latest-posts"><a href="#">
                <div class="post d-flex align-items-center">
                  <div class="image"><img src="{% static 'img/apple.ico' %}" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>Hotels for all budgets</strong><span class="date last-meta">October 26, 2016</span></div>
                </div></a><a href="#">
                <div class="post d-flex align-items-center">
                  <div class="image"><img src="{% static 'img/apple.ico' %}" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>Great street atrs in London</strong><span class="date last-meta">October 26, 2016</span></div>
                </div></a><a href="#">
                <div class="post d-flex align-items-center">
                  <div class="image"><img src="{% static 'img/apple.ico' %}" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>Best coffee shops in Sydney</strong><span class="date last-meta">October 26, 2016</span></div>
                </div></a></div>
          </div>
        </div>
      </div>
      <div class="copyrights">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <p>&copy; 2020. All rights reserved. Your great site.</p>
            </div>
            <div class="col-md-6 text-right">
              <p>Template By <a href="https://bootstrapious.com/p/bootstrap-carousel" class="text-white">Bootstrapious</a>
                <!-- Please do not remove the backlink to Bootstrap Temple unless you purchase an attribution-free license @ Bootstrap Temple or support us at http://bootstrapious.com/donate. It is part of the license conditions. Thanks for understanding :)                         -->
              </p>
            </div>
          </div>
        </div>
      </div>
    </footer>
       <!-- JavaScript files-->
       <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
       <script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"> </script>
       <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
       <script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
       <script src="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.js' %}"></script>
       <script src="{% static 'js/front.js' %}"></script>
   
</body>
</html>

MyStories/poems/templates/poems/blog.html
{% extends 'base.html' %}
{% load blog_tags %}
{% load staticfiles %}
{% block content %}

    <div class="container">
      <div class="row">
        <!-- Latest Posts -->
        <main class="posts-listing col-lg-8"> 
          <div class="container">
            <div class="row">
              <!-- post -->
              {% for post in posts %}
              <div class="post col-xl-6">
                <div class="post-thumbnail"><a href="{{post.get_absolute_url}}"><img src="{{post.thumb.url}}" alt="..." class="img-fluid"></a></div>
                <div class="post-details">
                  <div class="post-meta d-flex justify-content-between">
                    <div class="date meta-last">{{post.date}}</div>
                    <div class="category"><a href="{{post.get_absolute_url}}">{{post.title}}</a></div>
                  </div><a href="{{post.get_absolute_url}}">
                    <h3 class="h4">Meet the beutiful post: {{post.title}}</h3></a>
                  <p class="text">{{post.body|markdown|truncatewords_html:30}}</p>
                  <footer class="post-footer d-flex align-items-center">
                      <div class="avatar"><img src="{% static 'img/user.jpg' %}" width="25" height="25"></div>
                      <div class="title"><span>{{post.author.username}}</span></div>
                      <div class="date"><i class="icon-clock"></i></div>
                      <div class="comments meta-last"><i class="icon-comment"></i></div>
                  </footer>
                </div>
              </div>
              {% endfor %}
       
            <!-- Pagination -->
            <nav aria-label="Page navigation example">
              <ul class="pagination pagination-template d-flex justify-content-center">
          
              {% include 'pagination.html' with page=page_obj %}
               
              </ul>
            </nav>
          </div>
        </main>
        <aside class="col-lg-4">
          <!-- Widget [Search Bar Widget]-->
          <div class="widget search">
            <header>
              <h3 class="h6">Search the blog</h3>
            </header>
            
              <div class="form-group">
                <p>Search through {% total_posts %} posts!</p>
                <form action="{% url 'poems:search_result' %}" method="get">
                  <input name='q' type="text" placeholder="What are you looking for?">
                  <button type="submit" class="submit"><i class="icon-search"></i></button>
                </form>
              </div>
            
          </div>
          <!-- Widget [Latest Posts Widget]        -->
          <div class="widget latest-posts">
            <header>
              <h3 class="h6">Latest Posts</h3>
            </header>
            <div class="blog-posts">
                <div class="item d-flex align-items-center">
                  <img src="{% static 'img/clock.png' %}" width="80" height="80" class="img-fluid">
                  <div class="title">
                    <strong>{% show_latest_posts %}</strong>
                    <div class="d-flex align-items-center">
                    </div>
                  </div>
                </div>
              </div>
 
          </div>
          <!-- Widget [Categories Widget]-->
          <div class="widget categories">
            <header>
              <h3 class="h6">Most commented posts</h3>
            </header>
            {% get_most_commented_posts as most_commented_posts %}
            {% for post in most_commented_posts %}
            <div class="item d-flex justify-content-between">
              <a href="{{post.get_absolute_url}}">{{post.title}}</a>
            </div>
            {% endfor %}
          </div>
          <!-- Widget [Tags Cloud Widget]-->
          <div class="widget tags">       
            <header>
              <h3 class="h6">Create your account and publish awesome articles...</h3>
            </header>
            <ul class="list-inline">
              <li class="list-inline-item">
                <a href="{% url 'accounts:login' %}" class="tag">Login</a>
                <p><strong>And take full access to the site! </strong></p>
              </li>
              <li class="list-inline-item">
                <a href="{% url 'accounts:signup' %}" class="tag">Sign Up</a>
                <p><strong>If you don't have an account yet! </strong></p>
              </li>
      
            </ul>
          </div>
        </aside>
      </div>
      <div class="container">
        {% latest_photos %}
      </div>
    </div>
    
 
{% endblock %}

<!-- <p><a href="{% url 'poems:post_feed' item.id %}">Subscribe to my RSS feed</a></p> -->

MyStories/poems/templates/poems/cards-gallery.html
{% extends 'base.html' %}
{% block content %}

<section class="gallery-block cards-gallery">
	    <div class="container">
	        <div class="heading">
	          <h2>Company's gallery</h2>
	        </div>
	        <div class="row">
				{% for image in images %}
	            <div class="col-md-6 col-lg-4">
	                <div class="card border-0 transform-on-hover">
	                	<a class="lightbox" href="{{image.thumb.url}}">
	                		<img src="{{image.thumb.url}}" alt="Card Image" class="card-img-top">
	                	</a>
	                    <div class="card-body">
	                        <h6><a href="#">Added by {{image.author.username}} on {{image.date}}</a></h6>
	                        <p class="text-muted card-text">{{image.info}}</p>
	                    </div>
	                </div>
				</div>
				{% endfor %}
	            {% include 'pagination.html' with page=page_obj %}
	         </div>
	    </div>
</section>
<script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
<script>
    baguetteBox.run('.cards-gallery', { animation: 'slideIn'});
</script>
{% endblock %}

MyStories/poems/templates/poems/gallery.html
<!-- 
{% for photo in photos %}
    <div class="container list-content"> 
        <img src="{{photo.thumb.url}}" width="100%" height="auto">
        <p>{{photo.info}}</p>
        <p>{{photo.date}}</p>
    </div>
        
{% endfor %} -->

MyStories/poems/templates/poems/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{post.get_absolute_url}}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

MyStories/poems/templates/poems/pagination.html
<div class="pagination">
    <span class="step-links">
      {% if page.has_previous %}
      
      <li class="page-item">
      
      <p>
        <a href="?page={{ page.previous_page_number }}"><i class="fa fa-angle-left"></i></a>
        Page {{ page.number }} of {{ page.paginator.num_pages }}.
      </p>
      </li>
        
      {% endif %}
      <!-- <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}.
      </span> -->
        {% if page.has_next %}
        <li class="page-item">
          <p>
            Page {{ page.number }} of {{ page.paginator.num_pages }}
            <a href="?page={{ page.next_page_number }}"><i class="fa fa-angle-right"></i></a>
          </p>
          
        </li>        
        {% endif %}
    </span>
  </div>

MyStories/poems/templates/poems/post_detail.html
{% extends "base.html" %}
{% load blog_tags %}
{% load staticfiles %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<div class="container detail">
  <div class="row">
    <div class="post col-xl-7">
    <div><img src="{{post.thumb.url}}" alt="..." class="img-fluid"></div>
    <div class="post-details">
      <div class="post-meta justify-content-between">
        <div class="date meta-last">Published by {{post.author.username}}</div>
        <div class="category">{{post.publish}}</div>
      </div>
        <h3 class="h4">{{post.title}}</h3>
      <p class="text-muted">{{post.body|markdown}}</p>
      <p>
        <a href="{% url 'poems:post_share' post.id %}">
        Share this post
        </a>
      </p>
        {% with comments.count as total_comments %}
          <div class="comments meta-last"><i class="icon-comment">{{ total_comments }} comment{{ total_comments|pluralize }}</i></div>    
        {% endwith %}
      <footer class="post-footer align-items-center">
          <div class="comment">
            {% for comment in comments %}
                <h5 class="info">
                  Comment {{ forloop.counter }} by {{ comment.name }}
                  {{ comment.created }}
                  <i class="icon-clock"></i>
                </h5>
              {{ comment.body|markdown }}
            {% empty %}
              <p>There are no comments yet.</p>
            {% endfor %}  
          </div>
      </footer>
    </div>
    </div>

    <aside class="col-lg-3">
      <div class="comment-widget">
        {% if new_comment %}
        <h4>Your comment has been added.</h4>
        <h4>Add a new comment</h4>
        <form action="." method="post">
          {{ comment_form.as_p }}
          {% csrf_token %}
          <p><input class="button" type="submit" value="Add comment"></p>
        </form>
      
        {% else %}
          <h4>Add a new comment</h4>
          <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
          </form>
        {% endif %}
    </div>
        
    </aside>
  </div>
</div>

{% endblock %}