new_news/accounts/urls.py
from django.conf.urls import url
from .import views

app_name = 'accounts'

urlpatterns = [
    url('login/', views.login_view, name='login'),
    url('signup/', views.signup_view, name='signup'),
    url(r'^logout/$', views.logout_view, name='logout'),
]

new_news/new_news/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	path('', include('post.urls')),
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),
]


urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

new_news/post/urls.py
from django.conf.urls import url
from .import views

app_name = 'post'


urlpatterns = [
	url(r'^$', views.list_view, name='list_view'),
    url('create/', views.create_view, name='create'),
    url(r'^(?P<pk>\d+)/$', views.detail_view, name='detail'),
    # url(r'^(?P<slug>\w+)/$', views.detail_view, name='detail'),
] 

new_news/accounts/models.py
from django.db import models

# Create your models here.

new_news/post/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Post(models.Model):
	title = models.CharField(max_length=100)
	slug = models.SlugField()
	body = models.TextField()
	date = models.DateTimeField(auto_now_add=True)
	thumb = models.ImageField(default='default.png', blank=True)
	author = models.ForeignKey(User, default=None, null=True, on_delete=models.CASCADE)

	def __str__(self):
		return self.title

	def snippet(self):
		return self.body[:50]+'...'

	

new_news/post/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body', 'slug','thumb']

    

new_news/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.http import HttpResponse
from django.contrib.auth import login, logout
# Create your views here.

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid(): 
            user = form.save()
            # log the user in
            login(request, user)
            return redirect('post:list_view')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form':form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # # log the user in
            user = form.get_user()
            login(request, user)
            # return HttpResponse(user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('post:list_view')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('post:list_view')

new_news/post/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Post
from django.contrib.auth.decorators import login_required
from .forms import PostForm
# Create your views here.

def list_view(request):
	post = Post.objects.all().order_by('-date')
	return render(request, 'post/post_list.html', {'post':post})

def detail_view(request, pk):
	post = Post.objects.get(pk=pk)
	# return HttpResponse('ishladi')
	return render(request, 'post/post_detail.html', {'post':post})

@login_required(login_url='/accounts/login/')
def create_view(request):
	if request.method == 'POST':
		form = PostForm(request.POST, request.FILES)
		if form.is_valid():
			# save files to the db
			# form.save()
			instance = form.save(commit=False)
			instance.author = request.user
			instance.save()
			return redirect('post:list_view')
	else:
		form = PostForm()
	return render(request, 'post/post_create.html', {'form':form})

new_news/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<div class="content">
    <div class="jumbotron-login">
        <h1 style="font-family: 'Orbitron', sans-serif;"><b>Log In</b></h1>
        <!-- action sends the data to the given url -->
        <form class="site-form" action="{% url 'accounts:login' %}" method="post">
            {% csrf_token %}
            {{form.as_p}}
            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{request.GET.next}}">
            {% endif %}
            <input type="submit" value="Login">
            <p><a href="{% url 'accounts:signup' %}"><input type="button" value="SignUp"></a></p>
        </form>
    </div>
</div>


{% endblock %}

new_news/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<div class="content">
    <div class="jumbotron-signup">
        <h1 style="font-family: 'Orbitron', sans-serif;"><b>Sign Up please!</b></h1>

        <!-- action sends the data to the given url -->
        <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input class='sign-me' type="submit" value="SignUp">
        </form>

    </div>
</div>

{% endblock %}

new_news/post/templates/post/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Document</title>

	<link rel="stylesheet" href="{% static 'css/style.css' %}">

	<link href="https://fonts.googleapis.com/css?family=Fjalla+One&display=swap" rel="stylesheet">

	<link href="https://fonts.googleapis.com/css?family=Bungee+Inline|Noto+Serif+TC&display=swap" rel="stylesheet">

	<link href="https://fonts.googleapis.com/css?family=Bungee+Inline&display=swap" rel="stylesheet">

	<link href="https://fonts.googleapis.com/css?family=Bad+Script|Baloo|Baloo+Bhai|Monoton|Orbitron&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
	<!-- A grey horizontal navbar that becomes vertical on small screens -->
	<div class="navbar-container">
		<nav class="navbar navbar-expand-sm bg-none">

			<!-- Links -->
			<ul class="navbar-nav" style="font-size: 30px; font-family: 'Fjalla One', sans-serif;">
			 <li class="nav-item">
				<a class="nav-link" href="{% url 'post:list_view' %}"><img src="{% static 'images/home.png' %}" width="50" height="50" /></a>
			 </li>
			 <li class="nav-item add">
				<a class="nav-link new" href="{% url 'post:create' %}">ADD NEW</a>
	    	 </li>
			 
			  
			 <li class="nav-item">
			  <a class="nav-link admin" href="{% url 'admin:index' %}">ADMIN</a>
			</li>
			
			</ul>
			<ul class="navbar-nav ml-auto">
			 {% if user.is_authenticated %}
			 <li>
    		  <form class="logout-link" method="post" action="{% url 'accounts:logout' %}">
				{% csrf_token %}
				<button type="submit"><img src="{% static 'images/user.png' %}" width="40" height="40" />LOGOUT</button>
			  </form>
			 </li>
			 {% else %}
			  <li class="nav-item">
				<a class="nav-link logging" href="{% url 'accounts:login' %}"><img src="{% static 'images/user.png' %}" width="50" height="50" />LOGIN</a>
			  </li>
			  <li class="nav-item">
				<a class="nav-link signing" href="{% url 'accounts:signup' %}"><img src="{% static 'images/sign.png' %}" width="50" height="50">SIGNUP</a>
			  </li>
			  
			 {% endif %}
			</ul>
		</nav>
	</div>
	<div class="background">
		
	</div>

	{% block content %}

	{% endblock %}

</body>
</html>

new_news/post/templates/post/birnimalkj.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

new_news/post/templates/post/post_create.html
{% extends 'base.html' %}
{% load staticfiles %}



{% block content %}
<div class="container-addnew">
    <div class="jumbotron-addnew">
       <h2>Create an Awesome, New Article</h2> 
       <form class="site-form" action="{% url 'post:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %} 
        {{form.as_p}}
        <input class='post' type="submit" value="Post">
       </form>
      
    </div>
</div>
<script src="{% static 'js/slugify.js' %}"></script>
{% endblock %}

new_news/post/templates/post/post_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="content">
    <div class="jumbotron-detail">
        <img src="{{post.thumb.url}}" width="100%" height="auto">
        <h2 style="font-family: 'Baloo Bhai', cursive;" style="font-size: 50px;">{{post.title}}</h2>
        <p style="font-size: 22px; font-family: 'Baloo', cursive;"><b>{{post.body}}</b></p>
        <p style="font-family: 'Bungee Inline', cursive;">{{post.date}}</p>
    </div>
</div>

{% endblock %}

new_news/post/templates/post/post_list.html
{% extends 'base.html' %}

{% block content %}

<div class="content">
	<div class="jumbotron-list">
		{% for post in post %}
		<div class="container">
		<table>
			<tr>
				<td>
					<h1 style="font-family: 'Baloo Bhai', cursive;" style="font-size: 45px;"><a href="{% url 'post:detail' post.pk %}">{{post.title}}</a></h1>
					<p style="font-family: 'Times New Roman', serif;">{{post.snippet}}</p>
					<p style="font-family: 'Bungee Inline', cursive; font-size: 15px;">{{post.date}}</p>
					<p class="author">Added by {{ post.author.username }}</p>
				</td>
				<td>
					<a href="{% url 'post:detail' post.pk %}"><img src="{{post.thumb.url}}" width="300" height="150"></a>
				</td>
			</tr>
		</table>
		</div>
			
		{% endfor %}
	</div>	
</div>

{% endblock %}